// *** GENERATED BY COMMON/GENERATEHEADERS.PY *** 
// Class file to store common communication information 
package com.example.panotroller;
// ** BEGIN CONSTANT DEFINITIONS **
public class GeneratedConstants {
	// ** BEGIN INSTRUCTION DEFINITIONS **
	// Instruction pair: conn_conf
	public final static byte INST_CONN_REQ = (byte) 0b11000000;
	public final static byte INST_CONN_CONF = (byte) 0b01000000;
	// Instruction pair: led_color
	public final static byte INST_SET_LED = (byte) 0b10001000;
	public final static byte INST_CNF_LED = (byte) 0b00001000;
	// Instruction pair: motor_speed
	public final static byte INST_SET_MTR = (byte) 0b10001010;
	public final static byte INST_CNF_MTR = (byte) 0b00001010;
	// Instruction pair: ping_float
	public final static byte INST_PING_FLO = (byte) 0b10000001;
	public final static byte INST_PONG_FLO = (byte) 0b00000001;
	// Instruction pair: ping_int
	public final static byte INST_PING_INT = (byte) 0b10000010;
	public final static byte INST_PONG_INT = (byte) 0b00000010;
	// Instruction pair: stop_all
	public final static byte INST_STOP_ALL = (byte) 0b11111110;
	public final static byte INST_STPD_ALL = (byte) 0b01111110;

	// Other value: stop_all
	public final static byte START_BYTE = (byte) 0b00000000;

	// Other value: stop_all
	public final static int MESSAGE_LENGTH = (int) 6;

}
