// *** GENERATED BY COMMON/GENERATEHEADERS.PY *** 
// Class file to store common communication information 
package com.example.panotroller;
// ** BEGIN CONSTANT DEFINITIONS **
public class GeneratedConstants {
	// ** BEGIN INSTRUCTION DEFINITIONS **
	// Instruction pair: ping_int
	public final static byte INST_PING_INT = (byte) 0b10000010;
	public final static byte INST_PONG_INT = (byte) 0b00000010;
	// Instruction pair: error
	public final static byte INST_AN_ERROR = (byte) 0b10000100;
	public final static byte INST_AR_ERROR = (byte) 0b00000100;
	// Instruction pair: led_color
	public final static byte INST_SET_LED = (byte) 0b10000110;
	public final static byte INST_CNF_LED = (byte) 0b00000110;
	// Instruction pair: motor_speed
	public final static byte INST_SET_MTR = (byte) 0b10001000;
	public final static byte INST_CNF_MTR = (byte) 0b00001000;
	// Instruction pair: position
	public final static byte INST_GET_POS = (byte) 0b10001010;
	public final static byte INST_GOT_POS = (byte) 0b00001010;
	// Instruction pair: home
	public final static byte INST_HOME_POS = (byte) 0b10001100;
	public final static byte INST_HOMD_POS = (byte) 0b00001100;
	// Instruction pair: move
	public final static byte INST_MOVE_ABS = (byte) 0b10001110;
	public final static byte INST_MOVD_ABS = (byte) 0b00001110;
	// Instruction pair: ustep
	public final static byte INST_SET_USTEP = (byte) 0b10010000;
	public final static byte INST_CNF_USTEP = (byte) 0b00010000;
	// Instruction pair: mode
	public final static byte INST_SET_MODE = (byte) 0b10010010;
	public final static byte INST_CNF_MODE = (byte) 0b00010010;
	// Instruction pair: photo
	public final static byte INST_TRIG_PHOT = (byte) 0b10010100;
	public final static byte INST_TOOK_PHOT = (byte) 0b00010100;
	// Instruction pair: stop_all
	public final static byte INST_STOP_ALL = (byte) 0b11111110;
	public final static byte INST_STPD_ALL = (byte) 0b01111110;
	// Instruction pair: ping_float
	public final static byte INST_PING_FLOAT = (byte) 0b10000011;
	public final static byte INST_PONG_FLOAT = (byte) 0b00000011;

	// Other value: start_byte
	public final static byte START_BYTE = (byte) 0b00000000;

	// Other value: message_length
	public final static int MESSAGE_LENGTH = (int) 6;

	// Other value: default_microstep
	public final static int DEFAULT_MICROSTEP = (int) 8;

}
